name: CUDA Test
on: [push]

jobs:
  cuda-test:
    runs-on: ubuntu-latest
    container:
      image: registry.cn-hangzhou.aliyuncs.com/nvidia_cuda/cuda:12.1.1-base
      options: --security-opt label=disable
    env:
      RESOURCE_CLASS: large
    steps:
    - name: 设置资源属性
      run: echo "resource_class=$RESOURCE_CLASS" >> $GITHUB_ENV
      
    - name: 下载代码
      uses: actions/checkout@v4
      
    - name: 安装依赖
      run: pip install -r requirements.txt
      
    - name: 测试显卡
      run: |
        echo "===== 开始测试 ====="
        python gpu_test.py
        echo "===== 测试完成 ====="
