name: CUDA Test
on: [push]

jobs:
  cuda-test:
    runs-on: ubuntu-latest
    container:
      image: registry.cn-hangzhou.aliyuncs.com/nvidia_cuda/cuda:12.1.1-base
    steps:
    - name: 下载代码
      uses: actions/checkout@v4
      
    - name: 安装依赖
      run: pip install -r requirements.txt
      
    - name: 测试显卡
      run: python gpu_test.py
