name: Minimal CUDA Test
on: [push]

jobs:
  cuda-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install torch==2.1.0
    - run: python -c "import torch; print(f'CUDA: {torch.cuda.is_available()}')"
