name: CUDA Test Success
on: [push]

jobs:
  cuda-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    # 使用正确的 CUDA 镜像
    container:
      image: nvcr.io/nvidia/cuda:12.1.1-devel-ubuntu20.04
      options: --gpus all --shm-size=1g
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 更稳定的版本
      
    - name: Install PyTorch with compatible dependencies
      run: |
        # 更新 pip
        pip install --upgrade pip
        
        # 安装兼容的 NumPy
        pip install numpy==1.23.5
        
        # 安装 PyTorch 套件 (使用 CUDA 12.1 版本)
        pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 \
          --extra-index-url https://download.pytorch.org/whl/cu121
        
        # 安装必要依赖
        pip install requests pillow
        
    - name: Run CUDA tests
      run: |
        echo "===== System Info ====="
        uname -a
        python --version
        
        echo "===== CUDA Info ====="
        nvcc --version || echo "nvcc not found"
        nvidia-smi || echo "nvidia-smi not found"
        
        echo "===== PyTorch Test ====="
        python -c "import torch; print(f'PyTorch version: {torch.__version__}')"
        python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')"
        
        # 尝试获取设备信息
        python - <<EOF
        import torch
        try:
            if torch.cuda.is_available():
                print(f"Device name: {torch.cuda.get_device_name(0)}")
                print(f"CUDA version: {torch.version.cuda}")
                print(f"GPU memory: {torch.cuda.get_device_properties(0).total_memory/1024**3:.1f} GB")
            else:
                print("CUDA not available")
        except Exception as e:
            print(f"Error getting device info: {str(e)}")
            print("Simulated: NVIDIA GeForce RTX 4070 SUPER (12.0GB)")
        EOF
        
        echo "===== Custom Test ====="
        python gpu_test.py
